var a = 9876.10021
document.write("floor(9876.10021) gives downward integer value:   " + Math.floor(a))
document.write("<br>")
document.write("ceil(9876.10021) gives upward integer value:   " + Math.ceil(a))
document.write("<br>")
document.write("round(9876.60021) after point > 5 it gives upward value:   " + Math.round(9876.60021))
document.write("<br>")
document.write("round(9876.10021) after point < 5 it gives lower value:    " + Math.round(a))
document.write("<br>")
document.write("truc(9876.10021) gives before point integer value:   " + Math.trunc(a))
document.write("<br>")
document.write("max(2,44,6) gives maximum value:  "+Math.max(2,44,6))
document.write("<br>")
document.write("min(2,44,6) gives minimum value:  "+Math.min(2,44,6))
document.write("<br>")
document.write("pow(base,expo) power function 2^8  value:  "+Math.pow(2,8))
document.write("<br>")
document.write("sqrt(num) square root (64) value:  "+Math.sqrt(64))
document.write("<br>")
document.write("cbrt(num) cubic root (64) value:  "+Math.cbrt(64))
document.write("<br>")
document.write("abs(num) absolute (-64) value:  "+Math.abs(-64))
document.write("<br>")
document.write("PI value" + Math.PI)
document.write("<br>")
document.write("random() return random value between 0 to 1 :  " + Math.random())
document.write("<br>")
document.write("Math.floor(Math.random()*100) start 0 but end  is 10 :   " + Math.floor(Math.random()*10))
document.write("<br>")
