var str = "the quick brown fox jumps over the lazy dog";
document.writeln(str)
document.write(" <br> The Lenght of String is   " + str.length)
document.write("<br>")
document.write("touppercase():     " + str.toUpperCase())
document.write("<br>")
document.write("tolowecase():     " + str.toLowerCase())
document.write("<br>")
document.write("include(var) to check either is present or not :  " +str.includes("e"))
document.write("<br>")
document.write("startsWith(var) to check sentence is start this variable : " +str.startsWith("e"))
document.write("<br>")
document.write("EndsWith(var) to check sentence is ends this variable :  " +str.endsWith("g"))
document.write("<br>")
document.write("search(var) return index   "+ str.search("dog"))
document.write("<br>")
document.write("indexOf(var,startIndex) return index  : "+str.indexOf("h",0))
document.write("<br>")
document.write("lastindexOf(var,startIndex opposite) return index :  "+str.indexOf("e",-3))
document.write("<br>")
document.write("match(var) to match if value is present it return array otherwise show null:  "+str.match(/the/g))
document.write("<br>")
document.write("replace(search,newValue) to edit  :  "+str.replace("dog","dolphing"))
document.write("<br>")
document.write("trin() removes extra spaces :  "+ str.trim())
document.write("<br>")
document.write("charAt(index) return value : " + str.charAt(5))
document.write("<br>")
document.write("charcodeAt(index) return ascii number :  " + str.charCodeAt(5))
document.write("<br>")
document.write("String.fromCharcode(num) return ascii value :  " + String.fromCharCode(77))
document.write("<br>")
document.write("split(' ') makes array   " + str.split(""))
document.write("<br>")
document.write("concat() :   " +str.concat(".It happened."))
document.write("<br>")
document.write("slice(start,lenght) makes sub string :     " + str.slice(10,24))
document.write("<br>")